### PR TITLE
Fix ActionDispatch::DebugExceptions extension deprecation on rails 7.1

### PR DESCRIPTION
**Pull request by Vasfed**
### Issue # (if available)
This should fix https://github.com/reidmorrison/rails_semantic_logger/issues/203

### Description of changes
Added test for ActionDispatch::DebugExceptions and fixed couple of rails 7.1 deprecations in tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by alexmalus** [comment]
@reidmorrison could you spare some time looking into this PR? Thanks :pray:

**Comment by jordan-brough** [comment]
@reidmorrison would be great to have a version published with this 🙏 🙏

**Comment by hirowatari** [comment]
@reidmorrison Is there a particular reason you can't respond?  Could you please mark this gem as abandoned if you're not going to respond to PRs for 4+ months?

**Comment by reidmorrison** [comment]
Thank you for the Pull Request, especially the addition of tests. :tada:

**Pull request merged**
